# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\"8\n\x04User\x12\x11\n\tfirstname\x18\x01 \x01(\t\x12\x10\n\x08lastname\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\r\"N\n\x07\x41\x64\x64ress\x12\x14\n\x0chouse_number\x18\x01 \x01(\r\x12\x0e\n\x06street\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x01(\t\"\xdd\x01\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05items\x18\x02 \x03(\t\x12\x14\n\x0cis_completed\x18\x03 \x01(\x08\x12\x13\n\x04user\x18\x04 \x01(\x0b\x32\x05.User\x12\"\n\x10shipping_address\x18\x05 \x01(\x0b\x32\x08.Address\x12\x33\n\x0fitem_quantities\x18\x06 \x03(\x0b\x32\x1a.Order.ItemQuantitiesEntry\x1a\x35\n\x13ItemQuantitiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x1d\n\x0fGetOrderRequest\x12\n\n\x02id\x18\x01 \x01(\r\"\xe1\x01\n\x12\x43reateOrderRequest\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05items\x18\x02 \x03(\t\x12\x13\n\x04user\x18\x03 \x01(\x0b\x32\x05.User\x12\"\n\x10shipping_address\x18\x04 \x01(\x0b\x32\x08.Address\x12@\n\x0fitem_quantities\x18\x05 \x03(\x0b\x32\'.CreateOrderRequest.ItemQuantitiesEntry\x1a\x35\n\x13ItemQuantitiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\xf7\x01\n\x12UpdateOrderRequest\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05items\x18\x02 \x03(\t\x12\x14\n\x0cis_completed\x18\x03 \x01(\x08\x12\x13\n\x04user\x18\x04 \x01(\x0b\x32\x05.User\x12\"\n\x10shipping_address\x18\x05 \x01(\x0b\x32\x08.Address\x12@\n\x0fitem_quantities\x18\x06 \x03(\x0b\x32\'.UpdateOrderRequest.ItemQuantitiesEntry\x1a\x35\n\x13ItemQuantitiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32\x92\x01\n\x0cOrderService\x12&\n\x08GetOrder\x12\x10.GetOrderRequest\x1a\x06.Order\"\x00\x12,\n\x0b\x43reateOrder\x12\x13.CreateOrderRequest\x1a\x06.Order\"\x00\x12,\n\x0bUpdateOrder\x12\x13.UpdateOrderRequest\x1a\x06.Order\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDER_ITEMQUANTITIESENTRY._options = None
  _ORDER_ITEMQUANTITIESENTRY._serialized_options = b'8\001'
  _CREATEORDERREQUEST_ITEMQUANTITIESENTRY._options = None
  _CREATEORDERREQUEST_ITEMQUANTITIESENTRY._serialized_options = b'8\001'
  _UPDATEORDERREQUEST_ITEMQUANTITIESENTRY._options = None
  _UPDATEORDERREQUEST_ITEMQUANTITIESENTRY._serialized_options = b'8\001'
  _USER._serialized_start=16
  _USER._serialized_end=72
  _ADDRESS._serialized_start=74
  _ADDRESS._serialized_end=152
  _ORDER._serialized_start=155
  _ORDER._serialized_end=376
  _ORDER_ITEMQUANTITIESENTRY._serialized_start=323
  _ORDER_ITEMQUANTITIESENTRY._serialized_end=376
  _GETORDERREQUEST._serialized_start=378
  _GETORDERREQUEST._serialized_end=407
  _CREATEORDERREQUEST._serialized_start=410
  _CREATEORDERREQUEST._serialized_end=635
  _CREATEORDERREQUEST_ITEMQUANTITIESENTRY._serialized_start=323
  _CREATEORDERREQUEST_ITEMQUANTITIESENTRY._serialized_end=376
  _UPDATEORDERREQUEST._serialized_start=638
  _UPDATEORDERREQUEST._serialized_end=885
  _UPDATEORDERREQUEST_ITEMQUANTITIESENTRY._serialized_start=323
  _UPDATEORDERREQUEST_ITEMQUANTITIESENTRY._serialized_end=376
  _ORDERSERVICE._serialized_start=888
  _ORDERSERVICE._serialized_end=1034
# @@protoc_insertion_point(module_scope)
